### ISSUE TITLE
Unable to find puppetlabs/centos-6.5-64-puppet

### ISSUE THREAD

**Issue by rev42** [dwilbraham/revive-adserver-vagrant#4]
After executing vagrant up, I got following error: 
*The box 'puppetlabs/centos-6.5-64-puppet' could not be found or
could not be accessed in the remote catalog.*

**Comment by dwilbraham** [comment]
Updated to centos-6.6 and fixed multiple other problems caused by the move to puppet 4 in commit 
5b6ace3c34ac0e1b947c1a4b5dd1194b11f5e48c,
